# Generated by Django 2.0.7 on 2018-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='d4826085213',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=500)),
                ('fio', models.CharField(max_length=500)),
                ('born', models.CharField(max_length=500)),
                ('pass_num', models.CharField(max_length=500)),
                ('pass_date', models.CharField(max_length=500)),
                ('pass_issued', models.CharField(max_length=500)),
                ('inn', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=500)),
            ],
        ),
    ]
