# Generated by Django 2.0.7 on 2018-08-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180808_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d4826085213',
            name='born_place',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
