# Generated by Django 2.0.7 on 2018-08-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_d6168077734'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=500)),
                ('id_find', models.CharField(max_length=500)),
            ],
        ),
    ]
